version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  server:
    build: ./server
    ports:
      - "8081:8081"
      - "9201:9201"
    depends_on:
      - "redis"
    restart: unless-stopped
    command: yarn start
